### PR TITLE
Address DPLA-222.

### PR DESCRIPTION
**Pull request by markpbaggett**
**GitHub Issue**: [DLTN_XSLT-82](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/82)
**JIRA Ticket**: [DPLA-222](https://jira.lib.utk.edu/browse/DPLA-222)

## What does this Pull Request do?

This attempts to simplify our manifest catalog procedures to make it easier to review, approve, submit and merge.

## What's new?

All catalogs are now in a catalogs subdirectory alongside our XSL to match up with where they will be on server.  Also, all current XSL calls the updated file location.

## How should this be tested?

1. Take a DC transform to TSLA and a corresponding Sample Data File and test it.
2. Run the tslaqdctomods.xsl and test if IIIF manifests are generated appropriately.
3. Run the utcqdctomods.xsl and test if IIIF manifests are generated appropriately.

## Additional Notes:

This will cause validity issues in coredctomods transform since it's unaware of the transform that declares the global variable, but the processor should handle it appropriately.

[As said here](https://forums.asp.net/t/1049215.aspx?Access+parameters+one+xsl+file+into+another+xsl), If stylesheet A includes or imports stylesheet B it's ok for stylesheet A to use global variables/parameters defined in B. Moreover, it's ok for stylesheet B to use global variables/parameters defined in A (that would make stylesheet B invalid when used standalone of course). 

## Interested parties

@mlhale7 @CanOfBees

### CODE REVIEW

**Comment by CanOfBees** [comment]
I'd like to propose an alternative approach to this problem. Instead of updating individual collection-level transforms (e.g. knoxpublicdctomods.xsl, etc) with an `xsl:variable name="catalog" select="document('path/to/catalog.xml')"`, we could potentially use one transform (i.e. thumbnailscontentdmdctomods.xsl) with a very similar variable: `xsl:variable name="cat-coll" select="collection('path/to/catalogs/')"`.

The main difference here is what gets built into memory. In the first case, we're individually selecting an XML catalog file and then matching in it. In the second, we're grabbing all of the XML catalog files and then matching on them all. Potentially this is a little slower. I have a half-baked test that I'll need to articulate a bit later.

Quick note re testing:
The following line is from using memphisp13039coll1dctomods.xsl w/ the `collection()` in `thumbnailscontentdmdctomods`:
*** Average execution time over last 51 runs: 3.643741s (3643.741424ms)

The following line is from using memphisp13039coll1dctomods.xsl w/ the `document()` in `thumbnailscontentdmdctomods`:
*** Average execution time over last 51 runs: 3.715627s (3715.627162ms)

I'll include a better picture of testing process shortly. (sorry for the brevity).

**Comment by markpbaggett** [comment]
@CanOfBees, thanks for the suggestion.  Let's go ahead and incorporate this.  I'll push a new commit.

**Comment by markpbaggett** [comment]
@CanOfBees, let me know what you think.  Since QDC sets don't use imports or includes, I think we should stick with the document function over the collection function.

**Comment by CanOfBees** [comment]
@markpbaggett - that makes sense to me.

**Comment by markpbaggett** [comment]
@mlhale7, not sure how I screwed that up.  I deleted the variable declaration in the wrong style sheet and added one to another.  This should be good now.

**Pull request merged**
