### PR TITLE
Write metadata things for Crossroads Friends and Family.

### PR DESCRIPTION
**Pull request by markpbaggett**
**GitHub Issue**: [DLTN_XSLT-101](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/101)

## What does this Pull Request do?

Adds required things for the Friends and Family set to be added to DPLA.

## What's new?

* Added an xoai to MODS transform that can be used for this set but hopefully others as well.

## How should this be tested?

A description of what steps someone could take to:

* Does the transform validate in Oxygen using th Saxon 8.7 processor
* Using sample XML code, does the pull request doe what is intended
* If you have access to a Repox instance, does applying the pull request and touching all existing XSLT do what is intended.
* If you run a full Scema validation on the feed the transform(s) applies to(using Variety.js and DLTN Metadata QA), does every record have:
	* a titleInfo/title
	* a location/url
	* an accessCondition

## Additional Notes:

The name of the transform may change if we need to but, we can do that with git mv.

## Interested parties

@mlhale7

### CODE REVIEW

**Comment by mlhale7** [comment]
@markpbaggett - The XML still isn't validating simply because the typeOfResource value is capitalized instead of lowercase ("Text" instead of "text").

**Comment by markpbaggett** [comment]
> @markpbaggett - The XML still isn't validating simply because the typeOfResource value is capitalized instead of lowercase ("Text" instead of "text").

@mlhale7  :disappointed:.  Sorry about this.  Give me a little time and I'll get this fixed and also check for validity across the full set.

**Comment by markpbaggett** [comment]
@mlhale7, alright.  Things are 100% valid now.

**Comment by mlhale7** [comment]
@markpbaggett - one last thing. Given that not all items from Rhodes are part of Crossroads to Freedom (especially going forward), I think it would be beneficial to streamline how we are representing the provider name in the recordContentSource so it facets more cleanly in DPLA. Instead of "Rhodes College. Crossroads to Freedom" can we simply put in "Rhodes College", which corresponds with [LCNAF](http://id.loc.gov/authorities/names/n88258779)? Then we could break out "Crossroads to Freedom" to a relatedItem tag, like this: ```<relatedItem displayLabel="Project"><titleInfo><title>Crossroads to Freedom</title></titleInfo></relatedItem>```

**Comment by markpbaggett** [comment]
> @markpbaggett - one last thing. Given that not all items from Rhodes are part of Crossroads to Freedom (especially going forward), I think it would be beneficial to streamline how we are representing the provider name in the recordContentSource so it facets more cleanly in DPLA. Instead of "Rhodes College. Crossroads to Freedom" can we simply put in "Rhodes College", which corresponds with [LCNAF](http://id.loc.gov/authorities/names/n88258779)? Then we could break out "Crossroads to Freedom" to a relatedItem tag, like this: `<relatedItem displayLabel="Project"><titleInfo><title>Crossroads to Freedom</title></titleInfo></relatedItem>`

I think this is done now.

**Pull request merged**
