### PR TITLE
Update MTSU catalog.

### PR DESCRIPTION
**Pull request by markpbaggett**
**GitHub Issue**: [DLTN-237](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/237)

## What does this Pull Request do?

Adds missing manifests for MTSU.

## What's new?

In the last p.r., I failed to update MTSU's catalog post fixing the manifest catalog generator. This adds all good IIIF manifests.

## How should this be tested?

Run transform and look at manifests for MTSU buchanan specifically.

## Interested parties

@mlhale7

### CODE REVIEW

**Comment by mlhale7** [comment]
@markpbaggett - when running the existing buchanan transform against buchanan11, I'm not getting the IIIF URL written into the XML record. I'm not sure if thumbnailscontentdmdctomods.xsl is hitting this set?

**Comment by markpbaggett** [comment]
@mlhale7, so that's a different problem that has to do with the XSL here.  Let me spin up the old Repox vagrant and see if I can see what's happening.

**Comment by markpbaggett** [comment]
@mlhale7 hey, i couldn't get the vagrant to work, so I just updated the transform on the server real quick to see what would happen. I haven't updated catalogs or anything like that, but you should see the presentation api change in the thumbnails transform should be working.  Here is an example:

https://dpla.lib.utk.edu/repox/OAIHandler?verb=ListRecords&set=p13039coll2&metadataPrefix=MODS

If you do a quick "ctrl+f" for iiif you should see the manifests now point at the presentation api rather than the image api. Of course you won't see anything on the server for MTSU because it still doesn't have it's catalog there.

Am I missing what you're saying here?  Honestly, I don't know how you test this stuff (historically I've done that with Repox vagrant) so maybe I'm missing something?  Also, remember that Repox uses Saxon 8.7 which I don't think you get out of the box with Oxygen if you're testing that way.

**Comment by markpbaggett** [comment]
I went ahead and deployed this catalog since the other one wasn't accurate when I updated XSLT and catalogs earlier today.

**Pull request merged**
